# Generated by Django 5.2.8 on 2025-12-24 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/%Y/%m/')),
                ('read_level', models.IntegerField(choices=[(0, 'GUEST'), (1, 'STAFF'), (2, 'MANAGER'), (3, 'ADMIN')], default=1)),
                ('write_level', models.IntegerField(choices=[(0, 'GUEST'), (1, 'STAFF'), (2, 'MANAGER'), (3, 'ADMIN')], default=2)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'GUEST'), (1, 'STAFF'), (2, 'MANAGER'), (3, 'ADMIN')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
