# Generated by Django 5.2.8 on 2025-12-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdocument',
            name='content',
            field=models.TextField(blank=True, verbose_name='내용 요약'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/%Y/%m/', verbose_name='첨부 파일'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='read_level',
            field=models.IntegerField(choices=[(0, '스텝 (Staff)'), (1, '파트장 (Part Leader)'), (2, '팀장 (Team Leader)'), (3, '전체 (Admin)')], default=0, verbose_name='공개 범위'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='문서 제목'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='write_level',
            field=models.IntegerField(choices=[(0, '스텝 (Staff)'), (1, '파트장 (Part Leader)'), (2, '팀장 (Team Leader)'), (3, '전체 (Admin)')], default=1, verbose_name='수정 권한'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, '스텝 (Staff)'), (1, '파트장 (Part Leader)'), (2, '팀장 (Team Leader)'), (3, '전체 (Admin)')], default=0, verbose_name='직급'),
        ),
    ]
