# Generated by Django 5.2.8 on 2025-12-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_eventdocument_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('FACILITY', '시설팀'), ('OFFICE', '사무팀'), ('COOP', '업무협업팀')], default='COOP', max_length=20, verbose_name='대분류 (본부)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('NONE', '- (없음)'), ('SOUND', '무대음향'), ('LIGHT', '무대조명'), ('VIDEO', '무대영상'), ('GUIDE', '무대계도'), ('ACCOUNT', '회계팀'), ('HR', '인재관리팀')], default='NONE', max_length=20, verbose_name='중분류 (팀)'),
        ),
    ]
