# Generated by Django 5.2.8 on 2026-01-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
